[package]
name = "hvm"
version = "0.1.65"
edition = "2021"
description = "A lazy, beta-optimal, massively-parallel, non-garbage-collected and strongly-confluent functional compilation target."
repository = "https://github.com/Kindelia/HVM"
license = "MIT"
keywords = ["functional", "language", "runtime", "compiler", "target"]
categories = ["compilers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
test = true

[[bin]]
name = "hvm"
test = false

[dependencies]
itertools = { version = "0.10", optional = true }
num_cpus = { version = "1.13", optional = true }
regex = { version = "1.5.4",optional = true}
highlight_error = { version = "0.1.2", default-features = false, git = "https://github.com/FranchuFranchu/rust_highlight_error.git", branch = "no-std"}
clap = { version = "3.1.8", features = ["derive"], optional = true }
hashbrown = "0.12.3"
proptest = { version = "1.0", optional = true }

[features]
std = [
	"dep:proptest", 
	"dep:clap", 
	"dep:regex",
	"dep:num_cpus",
	"itertools/use_std",
]
default = ["std"]

[dev-dependencies]
